name: ci

on:
  push:
    branches:
      - main
      - develop
      - issues/*

env:
  server-directory: ./

jobs:
  server-ci:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby-version: [3.2.2]
    defaults:
      run:
        working-directory: ${{ env.server-directory }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run linter
      run: rubocop
    - name: Create db
      run: RAILS_ENV=test rails db:create
    - name: Migrate db
      run: RAILS_ENV=test rails db:migrate
    - name: Seed db
      run: RAILS_ENV=test rails db:seed
    - name: Run tests
      run: rails test
